# Generated by Django 4.0.4 on 2022-06-23 08:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post_comment',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Updated',
        ),
        migrations.AddField(
            model_name='post',
            name='Overview',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(blank=True, default='post-2.png', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='Topic_post',
        ),
        migrations.AddField(
            model_name='post',
            name='Topic_post',
            field=models.ManyToManyField(to='blog.topic'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
