# Generated by Django 4.0.4 on 2022-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(blank=True, default='post-2.png', null=True, upload_to=''),
        ),
    ]
