# Generated by Django 4.0.4 on 2022-06-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(blank=True, default='img/post-1.png', null=True, upload_to='img'),
        ),
    ]
